// Auto-generated by fit_underlying.py on 2026-02-24 — run to update.
// Contains Student-t MLE fit parameters to daily log-returns (last 10 years).
// 
// When simulating with a target portfolio IV, prob_charts.js recalculates
// the scale so the distribution's std = IV/sqrt(252), while keeping df
// fixed (preserving the historically-fitted tail shape).

const T_DIST_PARAMS_DB = {
    "SPY": {
        "df": 2.52973732,
        "loc": 0.00096109,
        "scale": 0.00616334
    },
    "AAPL": {
        "df": 3.01939758,
        "loc": 0.00128994,
        "scale": 0.01148903
    }
};
