// Auto-generated by spx_fit.py on 2026-02-23 — run to update.
// SPX (^GSPC) data: 2016-02-16 to 2026-02-23 (2518 trading-day observations)
//
// Student-t MLE fit to daily log-returns:
//   df    = 2.52973732   (degrees of freedom; controls tail fatness)
//   loc   = 0.00096109  (daily drift; ~0.2422 annualised)
//   scale = 0.00616334  (scale param — NOT the daily std)
//
// Daily std of this t-distribution = scale * sqrt(df/(df-2)) = 0.01346862
//   → 21.38% annualised vol
//
// When simulating with a target portfolio IV, prob_charts.js recalculates
// the scale so the distribution's std = IV/sqrt(252), while keeping df
// fixed (preserving the historically-fitted tail shape).
const T_DIST_PARAMS = {
    df:    2.52973732,
    loc:   0.00096109,
    scale: 0.00616334
};
