#!/usr/bin/env python3
"""
Underlying Student-t Distribution Fitting Script
==========================================
Downloads historical daily data for specified tickers for the last 10 years,
fits a Student-t distribution to the log-returns using MLE for each ticker,
and updates t_params_db.json and t_params_db.js for use by the browser Monte Carlo engine.

Usage:
    python fit_underlying.py [TICKER1] [TICKER2] ...
    Example: python fit_underlying.py SPY QQQ AAPL

Requirements:
    pip install yfinance scipy numpy pandas
"""

import sys
import numpy as np
import pandas as pd
import scipy.stats as ss
import yfinance as yf
from datetime import date, timedelta
import os
import json


def fit_ticker(ticker, start, end):
    print(f"\n--- Processing {ticker} ---")
    print(f"Downloading data from {start} to {end} ...")
    
    # Download data
    data = yf.download(ticker, start=str(start), end=str(end), auto_adjust=True, progress=False)

    if len(data) < 100:
        print(f"ERROR: Insufficient data downloaded for {ticker}.")
        return None

    print(f"  Downloaded {len(data)} trading days of data.")

    # Compute log returns
    close = data['Close'].squeeze()
    log_returns = np.log(close).diff().dropna()

    # Fit Normal (for comparison)
    norm_loc, norm_scale = ss.norm.fit(log_returns)
    
    # Fit Student-t
    df, loc, scale = ss.t.fit(log_returns)

    if df > 2:
        t_daily_std = scale * np.sqrt(df / (df - 2))
    else:
        t_daily_std = float('inf')

    print("Student-t fit (MLE):")
    print(f"  df    = {df:.8f}")
    print(f"  loc   = {loc:.8f}")
    print(f"  scale = {scale:.8f}")
    print(f"  implied annual vol = {t_daily_std * np.sqrt(252) * 100:.2f}%")

    return {
        "df": df,
        "loc": loc,
        "scale": scale
    }


def main():
    if len(sys.argv) < 2:
        print("Usage: python fit_underlying.py [TICKER1] [TICKER2] ...")
        print("Example: python fit_underlying.py SPY QQQ AAPL")
        return

    tickers = [t.upper() for t in sys.argv[1:]]

    # Timeframe
    end = date.today()
    start = end - timedelta(days=365 * 10 + 10)

    # Output to project root (parent of scripts/)
    script_dir = os.path.dirname(os.path.abspath(__file__))
    project_dir = os.path.dirname(script_dir)
    json_path = os.path.join(project_dir, "t_params_db.json")
    js_path = os.path.join(project_dir, "t_params_db.js")

    db = {}
    if os.path.exists(json_path):
        try:
            with open(json_path, 'r') as f:
                db = json.load(f)
            print(f"Loaded existing database with {len(db)} entries.")
        except Exception as e:
            print(f"Error loading existing database: {e}. Starting fresh.")
            db = {}

    # Process each ticker
    updated_count = 0
    for ticker in tickers:
        params = fit_ticker(ticker, start, end)
        if params:
            db[ticker] = params
            updated_count += 1

    if updated_count == 0:
        print("\nNo tickers were successfully processed.")
        return

    # Write out JSON DB
    with open(json_path, 'w') as f:
        json.dump(db, f, indent=4)
    print(f"\nSaved updated database to {json_path}")

    # Write out JS DB for browser inclusion
    js_content = f"""// Auto-generated by fit_underlying.py on {date.today()} — run to update.
// Contains Student-t MLE fit parameters to daily log-returns (last 10 years).
// 
// When simulating with a target portfolio IV, prob_charts.js recalculates
// the scale so the distribution's std = IV/sqrt(365), while keeping df
// fixed (preserving the historically-fitted tail shape).

const T_DIST_PARAMS_DB = {json.dumps(db, indent=4)};
"""
    with open(js_path, 'w') as f:
        f.write(js_content)
    print(f"Saved javascript database to {js_path}")
    print("Reload index.html in your browser to use the updated parameters.")


if __name__ == "__main__":
    main()
