#!/usr/bin/env python3
"""
SPX Student-t Distribution Fitting Script
==========================================
Downloads SPX (^GSPC) daily data for the last 10 years,
fits a Student-t distribution to the log-returns using MLE,
and writes t_params.js for use by the browser Monte Carlo engine.

Usage:
    python spx_fit.py

Requirements:
    pip install yfinance scipy numpy pandas
"""

import numpy as np
import pandas as pd
import scipy.stats as ss
import yfinance as yf
from datetime import date, timedelta
import os


def main():
    # --- 1. Download data (last 10 years) ---
    end = date.today()
    start = end - timedelta(days=365 * 10 + 10)   # +10 day buffer for weekends/holidays

    print(f"Downloading SPX (^GSPC) data from {start} to {end} ...")
    spx = yf.download("^GSPC", start=str(start), end=str(end), auto_adjust=True, progress=False)

    if len(spx) < 100:
        print("ERROR: Insufficient data downloaded. Check your internet connection.")
        return

    print(f"  Downloaded {len(spx)} trading days of data.")

    # --- 2. Compute log returns ---
    close = spx['Close'].squeeze()          # handle multi-level columns if present
    log_returns = np.log(close).diff().dropna()

    print(f"  Using {len(log_returns)} log-return observations.\n")

    # --- 3. Fit Normal (for comparison / sanity check) ---
    norm_loc, norm_scale = ss.norm.fit(log_returns)
    print("Normal fit:")
    print(f"  mu    = {norm_loc:.8f}  ({norm_loc * 252:.4f} annualised mean)")
    print(f"  sigma = {norm_scale:.8f}  ({norm_scale * np.sqrt(252) * 100:.2f}% annualised vol)\n")

    # --- 4. Fit Student-t ---
    df, loc, scale = ss.t.fit(log_returns)

    if df > 2:
        t_daily_std = scale * np.sqrt(df / (df - 2))
    else:
        t_daily_std = float('inf')

    print("Student-t fit (MLE):")
    print(f"  df    = {df:.8f}  (degrees of freedom — controls tail fatness)")
    print(f"  loc   = {loc:.8f}  ({loc * 252:.4f} annualised drift)")
    print(f"  scale = {scale:.8f}  (scale parameter; NOT the daily std)")
    print(f"  implied daily std  = {t_daily_std:.8f}")
    print(f"  implied annual vol = {t_daily_std * np.sqrt(252) * 100:.2f}%\n")

    # Interpretation note
    print(f"  A df ≈ {df:.1f} indicates {'strong' if df < 4 else 'moderate'} fat-tail behaviour.")
    print(f"  Normal fit gives annual vol {norm_scale * np.sqrt(252) * 100:.2f}% vs")
    print(f"  t-dist implied  {t_daily_std * np.sqrt(252) * 100:.2f}%.\n")

    # --- 5. Write t_params.js ---
    script_dir = os.path.dirname(os.path.abspath(__file__))
    out_path = os.path.join(script_dir, "t_params.js")

    content = f"""// Auto-generated by spx_fit.py on {date.today()} — run to update.
// SPX (^GSPC) data: {start} to {end} ({len(log_returns)} trading-day observations)
//
// Student-t MLE fit to daily log-returns:
//   df    = {df:.8f}   (degrees of freedom; controls tail fatness)
//   loc   = {loc:.8f}  (daily drift; ~{loc * 252:.4f} annualised)
//   scale = {scale:.8f}  (scale param — NOT the daily std)
//
// Daily std of this t-distribution = scale * sqrt(df/(df-2)) = {t_daily_std:.8f}
//   → {t_daily_std * np.sqrt(252) * 100:.2f}% annualised vol
//
// When simulating with a target portfolio IV, prob_charts.js recalculates
// the scale so the distribution's std = IV/sqrt(252), while keeping df
// fixed (preserving the historically-fitted tail shape).
const T_DIST_PARAMS = {{
    df:    {df:.8f},
    loc:   {loc:.8f},
    scale: {scale:.8f}
}};
"""

    with open(out_path, "w") as f:
        f.write(content)

    print(f"t_params.js written to: {out_path}")
    print("Reload index.html in your browser to use the updated parameters.")


if __name__ == "__main__":
    main()
