'use strict';

/**
 * Frozen workspace fixtures for the persistence snapshot contract
 * (sessionSchemaVersion 1). Three shapes:
 *
 *   minimal — a bare live workspace, nothing optional present.
 *   complex — a fully populated workspace mid-live-session, including every
 *             category of runtime/broker evidence the snapshot must scrub.
 *   legacy  — a pre-schema (version 0) file: top-level legs, dte instead of
 *             expDate, and the historical allowLiveComboOrders leak.
 *
 * Each factory returns a fresh deep copy so tests can mutate freely.
 */

function minimalWorkspaceState() {
    return {
        underlyingSymbol: 'SPY',
        underlyingContractMonth: '',
        underlyingPrice: 500,
        baseDate: '2026-08-03',
        simulatedDate: '2026-08-03',
        marketDataMode: 'live',
        historicalQuoteDate: '',
        interestRate: 0.03,
        ivOffset: 0,
        greeksEnabled: false,
        allowLiveComboOrders: false,
        allowLiveHedgeOrders: false,
        liveComboOrderAccounts: [],
        liveComboOrderAccountsConnected: false,
        selectedLiveComboOrderAccount: '',
        forwardRateSamples: [],
        futuresPool: [],
        groups: [],
        hedges: [],
    };
}

function complexWorkspaceState() {
    return {
        underlyingSymbol: 'SPY',
        underlyingContractMonth: '',
        underlyingPrice: 632.25,
        baseDate: '2026-08-03',
        simulatedDate: '2026-08-05',
        marketDataMode: 'live',
        historicalQuoteDate: '',
        historicalAvailableStartDate: '2024-01-02',
        historicalAvailableEndDate: '2026-08-01',
        historicalTradingDates: ['2026-07-31', '2026-08-01'],
        marketDataModeLocked: true,
        interestRate: 0.035,
        ivOffset: 0.01,
        greeksEnabled: true,
        equityOptionPricingModel: 'american-binomial',
        fopOptionPricingModel: 'black76',
        equityDividendYield: 0.012,
        americanBinomialSteps: 96,
        useMarketDiscountCurve: true,
        discountCurve: { curveDate: '2026-08-04', nodes: [{ days: 30, rate: 0.0525 }] },
        discountCurveLastError: 'stale runtime error',
        discountCurveLastLoadedAt: '2026-08-05T13:30:00Z',
        discountCurveLastResponseStatus: 'ok',
        discountCurveLastLoadWasManual: false,
        discountCurveRequestManual: false,
        discountCurveRequestPending: true,
        simTimeBasis: 'weighted',
        simWeekendWeight: 0.3,
        simUseImpliedLambda: true,
        simImpliedLambdaEntry: { lambda: 0.31 },
        simImpliedLambdaFileEntry: null,
        simImpliedLambdaCoverage: { start: '2026-07-01' },
        simulationTiming: { asOf: '2026-08-05T14:00:00Z' },
        simulationTargetAsOf: '2026-08-05T20:00:00Z',
        projectionConvergenceMode: 'best-effort-input-iv',
        liveProjectionFeedConnected: true,
        liveProjectionFeedStale: false,
        liveProjectionLastReceivedAt: '2026-08-05T14:00:01Z',
        liveQuoteDate: '2026-08-05',
        liveQuoteAsOf: '2026-08-05T14:00:02Z',
        liveSubscriptionUnresolvedById: { leg_live: 'pending' },
        liveFuturesRequestGeneration: 17,
        pendingLegExistsCheckGroupId: 'group_main',
        requireExactContractTiming: true,
        primaryControlPanelCollapsed: false,
        forwardRatePanelCollapsed: true,
        futuresPoolPanelCollapsed: false,
        viewMode: 'combined',
        workspaceVariant: 'default',
        importedSessionTitle: 'SPY_2026-08-05',
        comboTemplateQuoteRequests: { 'req-1': { pending: true } },
        globalEquivalentClose: { status: 'previewed', closePlanToken: 'never-save-me' },
        portfolioPositions: [{ account: 'U1111111', conId: 12345, position: -2 }],
        portfolioPositionsConnected: true,
        allowLiveComboOrders: true,
        allowLiveHedgeOrders: true,
        liveComboOrderAccounts: ['U1111111', 'U99999999'],
        liveComboOrderAccountsConnected: true,
        selectedLiveComboOrderAccount: 'U1111111',
        deltaHedge: {
            enabled: true,
            targetDelta: 0,
            tolerance: 25,
            proactiveBuffer: 5,
            hedgeInstrument: {
                secType: 'STK',
                symbol: 'SPY',
                exchange: 'SMART',
                currency: 'USD',
                contractMonth: '',
                multiplier: 1,
                deltaPerUnit: 1,
                conversionRatio: 1,
            },
            orderType: 'LMT',
            limitPrice: null,
            limitOffset: 0.01,
            maxOrderQuantity: 500,
            autoMaxNotional: 100000,
            cooldownSeconds: 90,
            autoSubmitEnabled: true,
            autoCancelStaleOrders: true,
            autoMaxOrdersPerDay: 3,
            autoPreviewMaxAgeSeconds: 30,
            pendingOrder: { orderId: 6021 },
            autoLastDecision: { action: 'submit' },
        },
        forwardRateSamples: [{
            id: 'sample_1',
            daysToExpiry: 45,
            expDate: '2026-09-18',
            strike: 630,
            dailyCarry: 0.00042,
            carryRate: 0.153,
            impliedRate: 0.051,
            forwardPrice: 633.4,
            spotPrice: 632.25,
            discountRate: 0.0525,
            discountFactor: 0.9935,
            discountSource: 'treasury-curve',
            quoteAsOf: '2026-08-05T14:00:00Z',
            expiryAsOf: '2026-09-18T20:00:00Z',
            quoteSkewMs: 120,
            tenorSeconds: 3888000,
            tenorDays: 45,
            timeYears: 0.1233,
            unavailableReason: '',
            quality: { grade: 'good' },
            lastComputedAt: '2026-08-05T14:00:03Z',
            isStale: false,
        }],
        futuresPool: [{
            id: 'future_1',
            contractMonth: '202609',
            bid: 6331.25,
            ask: 6331.75,
            mark: 6331.5,
            lastQuotedAt: '2026-08-05T14:00:04Z',
        }],
        groups: [{
            id: 'group_main',
            name: 'Aug dc rfly',
            includedInGlobal: true,
            isCollapsed: false,
            liveData: true,
            livePriceMode: 'midpoint',
            settleUnderlyingPrice: null,
            historicalAutoCloseAtExpiry: true,
            syncAvgCostFromPortfolio: true,
            viewMode: 'active',
            tradeTrigger: {
                enabled: true,
                condition: 'gte',
                price: 640,
                executionMode: 'submit',
                repriceThreshold: 0.01,
                timeInForce: 'DAY',
                exitEnabled: false,
                exitCondition: 'lte',
                exitPrice: null,
                isExpanded: true,
                status: 'armed',
                pendingRequest: true,
                lastTriggeredAt: '2026-08-05T13:59:00Z',
                lastTriggerPrice: 640.05,
                lastPreview: { orderId: 6022, status: 'PreSubmitted' },
                lastError: 'old error',
            },
            closeExecution: {
                executionMode: 'test_submit',
                strategy: 'auto',
                quantity: null,
                quantityMode: 'auto',
                repriceThreshold: 0.01,
                timeInForce: 'DAY',
                isExpanded: false,
                status: 'submitted',
                pendingRequest: true,
                lastPreview: { orderId: 6023 },
                lastError: '',
            },
            legs: [
                {
                    id: 'leg_manual',
                    type: 'put',
                    pos: -2,
                    strike: 600,
                    expDate: '2026-09-18',
                    cost: 4.35,
                    costSource: 'manual',
                    closePrice: null,
                    currentPrice: 4.1,
                    currentPriceSource: 'manual',
                    iv: 0.24,
                    ivSource: 'manual',
                    ivManualOverride: true,
                    portfolioMarketPrice: 4.05,
                    portfolioMarketPriceSource: 'tws',
                    portfolioMarketPriceAsOf: '2026-08-05T14:00:05Z',
                    portfolioUnrealizedPnl: 60,
                    underlyingFutureId: '',
                    executionReportOrderId: 6001,
                    executionReportPermId: 998877,
                    executionReportedCost: 4.35,
                },
                {
                    id: 'leg_live',
                    type: 'call',
                    pos: 1,
                    strike: 650,
                    expDate: '2026-09-18',
                    cost: 2.1,
                    costSource: 'manual',
                    closePrice: null,
                    currentPrice: 2.42,
                    currentPriceSource: 'live',
                    iv: 0.19,
                    ivSource: 'live',
                    ivManualOverride: false,
                    portfolioMarketPrice: 2.41,
                    portfolioMarketPriceSource: 'tws',
                    portfolioMarketPriceAsOf: '2026-08-05T14:00:06Z',
                    portfolioUnrealizedPnl: 32,
                    underlyingFutureId: '',
                    expiryAsOf: '2026-09-18T20:00:00.000Z',
                    expiryTimingSource: 'ib_contract_details',
                    lastTradeDate: '20260918',
                    lastTradeTime: '16:00:00',
                    expiryTimeZoneId: 'US/Eastern',
                    realExpirationDate: '20260918',
                    qualifiedOptionConId: 771234,
                    qualifiedOptionLocalSymbol: 'SPY 260918C650',
                    qualifiedOptionTradingClass: 'SPY',
                    qualifiedOptionUnderConId: 756733,
                    qualifiedOptionUnderlyingContractMonth: '',
                    liveQuoteIdentityStatus: 'verified',
                    liveQuoteIdentityReason: '',
                },
                {
                    id: 'leg_closed',
                    type: 'call',
                    pos: 1,
                    strike: 620,
                    expDate: '2026-08-15',
                    cost: 3.2,
                    costSource: 'manual',
                    closePrice: 5.05,
                    currentPrice: 0,
                    currentPriceSource: '',
                    iv: 0.21,
                    ivSource: 'manual',
                    ivManualOverride: false,
                    underlyingFutureId: '',
                },
            ],
        }],
        hedges: [{
            id: 'hedge_1',
            symbol: 'SPY',
            pos: 100,
            price: 631.8,
        }],
    };
}

function legacyV0ImportPayload() {
    return {
        underlyingSymbol: 'GLD',
        underlyingPrice: 310,
        baseDate: '2026-07-01',
        daysPassed: 5,
        interestRate: 0.04,
        allowLiveComboOrders: true,
        allowLiveHedgeOrders: true,
        selectedLiveComboOrderAccount: 'U1111111',
        legs: [
            { type: 'call', dte: 30, pos: 1, strike: 315, cost: 2.4, iv: 0.18 },
            { type: 'put', dte: 30, pos: 1, strike: 305, cost: 2.1, iv: 0.2 },
        ],
        hedges: [
            { symbol: 'GLD', pos: -50 },
        ],
    };
}

module.exports = {
    minimalWorkspaceState,
    complexWorkspaceState,
    legacyV0ImportPayload,
};
